config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

  devise_for :users
  # get 'home/index'
  resources :users
  resources :tasks
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user ,  :optional => true

# after_save_commit do
#     if due_date_previously_changed?
#         RemainderJob.set(wait_until: due_date.to_s).perform_later(self)
#     end
# end

end

app/models/user.rb
class User < ApplicationRecord
  # require 'csv'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :confirmable
    has_many :tasks
  
  validates:first_name,presence: true
  validates:last_name,presence: true
  validates:email,presence: true
  # def self.to_csv(collection)
  #   CSV.generate(col_sep: ";") do |csv|
  #     csv << attribute_names
  #     collection.find_each do |record|
  #       csv << record.attributes.values
  #     end
  #   end
  # end



  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    helper :all
    before_action :set_locale

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :dob])
    end

    
    private
    def set_locale
        I18n.locale = extract_locale || I18n.default_locale
    end

    def extract_locale
        parsed_locale = params[:locale]
        I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
    end
    private
    def default_url_options
        { locale: I18n.locale }
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.js   { render "tasks/task", :layout => false }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  helper_method :test
  skip_before_action :verify_authenticity_token, only:  %i[update  create]


  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
      respond_to do |format|
        format.html
        format.pdf do
          pdf = TaskPdf.new(@tasks)
          send_data pdf.render , filename: 'member.pdf' , type: 'application/pdf', disposition: "inline"
        end
        format.csv do
        end
      end 
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end


  #mail
  def task_mailer
    @user = User.all
    byebug
  end
  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.name.capitalize!
    @user = User.find_by_id(@task.user_no)
    puts @user.inspect
    if Task.where(name:@task.name).count>0
      respond_to do |format|
        format.html { redirect_to tasks_path(@task), notice:["Task was Already Exist", 0] }
      end
    else
    respond_to do |format|
      if @task.save
        # UserMailer.with(user: @user,task: @task).task_assigned.deliver_now
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        @user = User.find_by_id(@task.user_no)
        # UserMailer.with(user: @user,task: @task).task_updated.deliver_now
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :due_date, :Status , :user_no)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  require 'csv'
  # GET /users or /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.pdf do
        pdf = MemberPdf.new(@users)
        send_data pdf.render , filename: 'member.pdf' , type: 'application/pdf', disposition: "inline"
      end
      format.csv do
      
      end
    end
    # respond_to do |format|
    #   format.html
    #   format.csv do 
    #     send_data User.to_csv(@users), filename: Date.today.to_s, content_type:'text/csv'
    #   end
    # end 
  end

  # GET /users/1 or /users/1.json
  def show
    # @value = 0
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    # @user.first_name.capitalize!
    # @user.last_name.capitalize!

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  # def with_task(tasks)
    # @ha = @user.joins(:tasks).where(tasks: {id: tasks})
  # end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :dob)
    end
end
# def with_task(tasks)
#   joins(:tasks).where(tasks: {id: tasks})
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<%# <h1>hello cbe</h1> %>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Tasklist',root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%# <%= link_to "Users" , users_path , class: "nav-link"%> 
            <%= link_to t('link.user_list') , users_path , class: "nav-link"%>
            <%# <a class="nav-link" href="#">Link</a> %>
          </li>

          <li class="nav-item">
            <%# <%= link_to "Tasks" , tasks_path , class: "nav-link"%> 
            <%= link_to t('link.task_list') , tasks_path , class: "nav-link"%>
            <%# <a class="nav-link" href="#">Link</a> %>
          </li>

          <li class="nav-item">
            <%# <%= link_to "edit profile" , edit_user_registration_path , class: "nav-link"%> 
            <%= link_to t('link.edit_profile') , edit_user_registration_path , class: "nav-link"%>           
            <%# <a class="nav-link" href="#">Link</a> %>
          </li>

          <li class="nav-item">
            <%# <%= button_to "Sign out" , destroy_user_session_path , method: :delete, class: "nav-link"%>
            <%= button_to t('link.sign_out') , destroy_user_session_path , method: :delete, class: "nav-link"%>
            <%# <a class="nav-link" href="#">Link</a> %>
          </li>
        <%else%>
          <li class="nav-item">
            <%# <%= link_to "Sign In" , new_user_session_path , class: "nav-link"%> 
            <%= link_to  t('link.sign_in') , new_user_session_path , class: "nav-link"%>
            <%# <a class="nav-link" href="#">Link</a> %>
          </li>

          <li class="nav-item">
            <%# <%= link_to "Sign Up" , new_user_registration_path , class: "nav-link"%>
            <%= link_to  t('link.sign_up') , new_user_registration_path , class: "nav-link"%>
            <%# <a class="nav-link" href="#">Link</a> %>
          </li>
        <%end%>

        
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<h1><%= t('static_content.hello')%></h1>
<%# <p>Find me in app/views/home/index.html.erb</p> %>

<%# <p>WElCOME TO TASKLIST WEBSITE</p> %>

<%= t('static_content.welcome') %>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>

app/views/layouts/application.html.erb
<%# <!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%# <%= csp_meta_tag %> 

    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
  <%#
    <%= javascript_importmap_tags %> 

  <%# <body>
    <%= yield %>
  <%# </body> %>
<%# </html> %> 



<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Tasklist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', :media => "all" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header'%>
    <div class = "container">
    <br/>
    <% if notice %>
      <%= render 'layouts/alert'%>
    <% end %>
    <%# <br> %>
    <%= yield %>
      <div class="container-fluid m-auto">
        <br>
          <%= link_to "English", root_path(locale: :en)%> |
          <%= link_to "Spainish", root_path(locale: :es)%>
        <br>
      </div>    
    </div>
    <%# #ajax %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <%# <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <%# <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> %>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <%# <div>
    <%= form.label :user_no, style: "display: block" %>
    <%# <%= form.text_field :user_no %>
  <%# </div> %>

  <%# <div>
    <%= form.label :Status, style: "display: block" %>
    <%# <%= form.check_box :Status %> 
  <%# </div> %>

<div class="mb-3 row">
    <%= form.label :Status, style: "display: block" %>
    (Completed/pending)
        <div>
    <%= form.check_box :Status ,class:"form-check-input"%>
  </div>
  </div>

  <% value={} %>
<% User.all.each {|val| value[val.id] = val.first_name}%>
  <div class="mb-3 row">
    <%= form.label :User, style: "display: block" %>
    <div class="col-sm-4">
      <%= form.select :user_no, :user_lists => value.sort.map {|k,v| [v,k]} %>
  </div>
  </div>

  <div>
    <%# <%= form.submit %>
    <%= form.submit class: "btn btn-success",remote: true %>
  </div>
<% end %>

app/views/tasks/_form2.html.erb
  <%= form_for @task, remote: true ,html: {class: "update"} do |form| %> 
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 row">
    <%= form.label :name,style: "display: block", class:"col-sm-4 col-form-label" %>
       <div class="col-sm-4">
    <%= form.text_field :name, class:"form-control col-6" %>
  </div>
  </div>

  <div class="mb-3 row">
    <%= form.label :due_date, style: "display: block", class:"col-sm-4 col-form-label" %>
      <div class="col-sm-4">  
    <%= form.date_field :due_date, class:"form-control col-6" %>
  </div>
  </div>

  <div class="mb-3 row">
    <%= form.label :Status, style: "display: block", class:"col-sm-4 col-form-label" %>
   (Completed/pending)
        <div class="col-sm-4">
    <%= form.check_box :Status ,class:"form-check-input"%>
  </div>
  </div>

  <% value={} %>
<% User.all.each {|x| value[x.id] = x.first_name}%>
  <div class="mb-3 row">
    <%= form.label :User, style: "display: block", class:"col-sm-4 col-form-label" %>
   <div class="col-sm-4">
    <%= form.select :user_no,value.sort.map {|k,v| [v,k]} , id: "select" %>
  </div>
  </div>

  <div class="mb-3 row col-4 m-auto">
 <%= form.submit "update",class: "btn btn-success",remote: true %>
      </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Name:</strong>
    <%= task.name %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= task.due_date %>
  </p>



  <p>
    <strong>Status:</strong>
    <%if task.Status == true %>
      <%= "completed" %>
    <%else%>
      <%= "Pending" %>
    <%end%>

  <%# <%= link_to "Show this task", task %> 
</div>

app/views/tasks/_taskCard.html.erb
<div class="card">
    <div class="card-header">
        <center>Current task Details </center>
    </div>
    <div class="card-body">
    <h5> <%= task.name %> |
    <%= task.due_date %> </h5>
    <p class="card-text"> <% if task.Status %>
    <span class="text-white bg-success"><%="Completed"%></span>
    <% else%>
    <span class="text-white bg-danger"><%= "Pending" %> </span>
    <%end%>
    </p>
    <%# <%= link_to "Edit this task", edit_task_path(@task), class:"btn btn-warning m-3" %> 
    <%# <%= link_to "Back to task", tasks_path,class:"btn btn-secondary m-3"  %>
    <%= link_to t('action.edit_task'), edit_task_path(@task), class:"btn btn-warning m-3" %> 
    <%= link_to t('action.back_task'), tasks_path,class:"btn btn-secondary m-3"  %>
    </div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%# <%= render "form", task: @task %> 
<p id="success"><p>
<%= render "form2",task: @task %>
<br>

<div>
  <%# <%= link_to "Show this task", @task %> |
  <%# <%= link_to "Back to tasks", tasks_path %>
  <%= link_to t('action.show_task'), @task %> |
  <%= link_to t('action.back_task'), tasks_path %>
</div>

app/views/tasks/index.csv.erb
<%= CSV.generate_line(["name","due_date","Status","user_no","created_at","updated_at"])%>
<% @tasks.each do |task|%>
<%= CSV.generate_line([task.name,task.due_date,task.Status,task.user_no,task.created_at,task.updated_at])%>
<% end%>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<%# <div id="tasks"> %>
  <%# <% @tasks.each do |task| %> 
    <%# <%= render task %> 
    <%# <p> %>
      <%# <%= link_to "Show this task", task %> 
    <%# </p> %>
  <%# <% end %> 
<%# </div> %>

<%# <%= link_to "New task", new_task_path  %>
<div id = "task">
<table class="table table-bordered table-hover">
  <thead class="thead-dark" >
    <tr>
      <th>Name</th>
      <th>Due_date</th>
      <th>Status</th>
      <th colspan = "3">Settings</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
            <tr>
        <td><%= task.name %></td>
        <td><%= task.due_date %></td>
        <td>
        <%if task.Status == true %>
          <%= "completed" %>
        <%else%>
          <%= "Pending" %>
        <%end%>
        </td>
        <%# <td><%= link_to "Show this task",task %></td>
        <%# <td><%= link_to "Edit this task", edit_task_path(task) %>
        <td><%= link_to t('action.show_task'),task %></td>
        <td><%= link_to t('action.edit_task'), edit_task_path(task) %></td>
        <%# <td><%= button_to "Destroy this task", @task, method: :delete %> 
      </tr>
    <% end %>
  </tbody>
</table>
  <%# <tr scope="row"> <%= render task %>
    <%# <% end %> 
  <%# </tbody> %>
<%# </table> %>
</div>

<%# <%= link_to "New task", new_task_path , class:"btn btn-secondary m-3" %>

<%= link_to t('link.new_task'), new_task_path , class:"btn btn-secondary m-3" %>

<%= link_to "Export as Csv", tasks_path(format: :csv) ,class:"btn btn-success m-3" %>

<%= link_to "Export as Pdf", tasks_path(format: 'pdf'), class:"btn btn-success m-3" %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%# <%= link_to "Back to tasks", tasks_path %>
  <%= link_to t('action.back_task'), tasks_path %>
</div>

app/views/tasks/show.html.erb
<%# <%= render @task %>

<%= render "tasks/taskCard",:task=>@task %>

<table class="table table-striped">
  <thead class="bg-light">
    <tr>
      <th></th>
      <th>First name</th>
      <th>Last name</th>
      <th>Dob</th>
      <th></th>
    </tr>
  </thead>
    <tbody>
<% User.where(id: @task.user_no).each do |user|%>
<tr><%= render "users/user", :user => user %>
</tr>
<%end%>
</tbody>
</table>

<div>
  <%# <%= link_to "Edit this task", edit_task_path(@task) %> 
  <%# <%= link_to "Back to tasks", tasks_path %>

  <%# <%= button_to "Destroy this task", @task, method: :delete %>
  <%= button_to t('action.destroy_task'), @task, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :dob, style: "display: block" %>
    <%= form.date_field :dob %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
      <td scope="row"></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.dob %></td>

</div>

app/views/users/_userCard.html.erb
<div>
    <div>
        <center>Current User Details </center>
    </div>
    <div class="card-body">
        <h5 class="card-title"> <%= user.first_name %>
        <%= user.last_name %> </h5>
        <p class="card-text"> <%= user.dob %> </p>
        <%# <%= link_to "Edit this user", edit_user_path(@user) %> 
        <%# <%= link_to "Back to users", users_path %>
        <%= link_to  t('action.edit_user'), edit_user_path(@user) %> 
        <%= link_to t('action.back_user'), users_path %>
    </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%# <%= link_to "Show this user", @user %> |
  <%# <%= link_to "Back to users", users_path %>
  <%= link_to t('action.show_user'), @user %> |
  <%= link_to t('action.back_user'), users_path %>
</div>

app/views/users/index.csv.erb
<%= CSV.generate_line(["Id","first_name","last_name","dob","created_at","updated_at","email","encrypted_password"])%>
<% @users.each do |user|%>
<%= CSV.generate_line([user.id,user.first_name,user.last_name,user.dob,user.created_at,user.updated_at,user.email,user.encrypted_password])%>
<% end%>

app/views/users/index.html.erb
<h1>Users</h1>

<%# <div id="users">
  <% @users.each do |user| %>
    <%# <%= render user %> 
    <%# <p> %>
      <%# <%= link_to "Show this user", user %> 
    <%# </p> %>
  <%# <% end %> 
<%# </div> %> 

<table class= "table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>DOB</th>
      <%# <th>Task</th> %>
      <th>Settings</th>
    </tr>
  </thead>
  <tbody>
  <%# <div id = "users"> %>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.dob %></td>
    <%# <%= render user %> 
      <td>
      <%# <%= link_to "Show this user", user %>
      <%= link_to t('action.show_user'), user %>
      </td>
      </tr>
    <% end %>
  <%# </div> %>
  </tbody>
</table>
<br/>
<%= link_to "New user", new_user_path , class:"btn btn-secondary m-3" %>


<%= link_to "Export as Csv", users_path(format: :csv) ,class:"btn btn-success m-3"%>
<%= link_to "Export as Pdf", users_path(format: 'pdf'), class:"btn btn-success m-3" %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%# <%= link_to "Back to users", users_path %>
  <%= link_to t('action.back_user'), users_path %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%# <%= render @user %>
<%= render "users/userCard",:user=>@user %>
  <%begin%>
  <%if Task.where(user_no: @user.id)[0].id>0%>
<table class="table">
  <thead>
    <%# <tr>
      <th>Task Name</th>
      <th>Due Date</th>
      <th>Status</th>
      <th></th>
    </tr> %>
  </thead>
  <tbody>
<% Task.where(user_no: @user.id).each do |task|%>

<tr scope="row"><%= render "tasks/task", :task => task %>
</tr>
<% end %>
  </tbody>
</table>

<%end%>
<%rescue %>
<p><%="NO task assigned for this user"%></p>
  <%end%>

<div>
  <%# <%= link_to "Edit this user", edit_user_path(@user) %> 
  <%# <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>